# Server Configuration
server:
  port: 8080

#Application Name
spring:
  application:
    name: jecuz

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/jecuz_db
    username: postgres
    password: root

  #Flyway Migration
  flyway:
    enabled: false
    baselineOnMigrate: false

  # Hibernate Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #E-mail Configuration
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: eng.ivancarlos85@gmail.com
    password: qdgn gxzm unos dmzq
    port: 587