# Database Configuration
spring:
  h2:
    console:
      enabled: 'true'

  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Server Configuration
server:
  port: 9000