# Database Configuration
spring:
  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  #Flyway Migration
  flyway:
    enabled: false
    baselineOnMigrate: false

#E-mail Configuration
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: eng.ivancarlos85@gmail.com
    password: qdgn gxzm unos dmzq
    port: 587

# Server Configuration
server:
  port: 8080