name: Continuous Delivery [CD]

on:
  push:
    branches: [ release ]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

  unitTest:
    needs: [ build ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Unit Test
        run: mvn test

  integrationTest:
    needs: [ build ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Integration Test
        run: mvn verify

  e2eTest:
    needs: [ build ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: e2e Test
        run: mvn test -Dtest="**/*E2ETest"

  smokeTest:
    needs: [ build ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: smoke Test
        run: mvn test -Dtest="**/*SmokeTest" -q

  package:
    needs: [ unitTest, integrationTest, smokeTest, e2eTest ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: packing application
        run: mvn -B package --file pom.xml -DskipTests -Xinstall

      - name: Verify Release O.S
        run: curl -fsSL https://raw.githubusercontent.com/ivancarlosantos/installer/refs/heads/master/release.sh | sh

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jecuz .

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/jecuz ${{ secrets.DOCKER_USERNAME }}/jecuz:release

      - name: Send Docker Image to Registry Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jecuz:release